# Generated by Django 3.2 on 2021-04-14 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('operator_email', models.EmailField(max_length=50)),
                ('operator_password', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('buyer_name', models.CharField(max_length=50)),
                ('buyer_address', models.CharField(max_length=254)),
                ('buyer_mobile_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10}$')])),
                ('donor_name', models.CharField(max_length=50)),
                ('donor_address', models.CharField(max_length=254)),
                ('donor_mobile_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10}$')])),
                ('donation_date', models.DateField(blank=True, help_text='YYYY/MM/DD - eg: 1998-02-27', null=True)),
                ('selling_date', models.DateField(blank=True, help_text='YYYY/MM/DD - eg: 1998-02-27', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('donor_name', models.CharField(max_length=50)),
                ('donor_address', models.CharField(max_length=254)),
                ('donor_mobile_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10}$')])),
                ('donation_date', models.DateField(blank=True, help_text='YYYY/MM/DD - eg: 1998-02-27', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='YYYY/MM/DD - eg: 1998-02-27', null=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.bloodbank')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
