# Generated by Django 3.1.7 on 2021-03-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bloodbank',
        ),
    ]
