# Generated by Django 3.2 on 2021-04-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='bloodbank_address',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
