# Generated by Django 3.2 on 2021-04-19 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0002_bloodbank_bloodbank_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
