# Generated by Django 3.1.7 on 2021-03-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0003_bloodbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='password',
        ),
    ]
