# Generated by Django 3.1.7 on 2021-03-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0005_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='donor_mobile_no',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='donor_name',
            field=models.CharField(max_length=50),
        ),
    ]
