# Generated by Django 3.1.7 on 2021-03-19 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0006_auto_20210319_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='donor_mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10}$')]),
        ),
    ]
