# Generated by Django 3.1.7 on 2021-03-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0007_inventory_donor_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='donation_date',
            field=models.DateField(blank=True, help_text='YYYY/MM/DD - eg: 1998/02/27', null=True),
        ),
    ]
