# Generated by Django 3.1.7 on 2021-03-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0018_auto_20210311_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('donor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.donor')),
                ('client', models.ManyToManyField(to='main.User')),
            ],
            bases=('main.donor',),
        ),
    ]
