# Generated by Django 3.1.7 on 2021-03-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0018_auto_20210311_0811'),
        ('bookmark', '0002_delete_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ManyToManyField(to='main.User')),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.donor')),
            ],
        ),
    ]
