# Generated by Django 3.1.6 on 2021-02-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210205_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
