# Generated by Django 3.1.6 on 2021-02-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_donor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
