# Generated by Django 3.1.6 on 2021-02-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210228_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_donor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
