# Generated by Django 3.1.6 on 2021-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210309_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_donor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
