# Generated by Django 3.1.6 on 2021-03-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210311_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
