# Generated by Django 3.1.6 on 2021-03-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210311_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(default='dhaka', max_length=50),
        ),
    ]
