# Generated by Django 3.1.6 on 2021-03-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210311_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
