# Generated by Django 3.1.7 on 2021-03-29 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210311_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
